Revert flask-jwt-extended upgrade
Upgrading flask-jwt-extended to 4.x breaks flask blueprinting in subtle ways, and entirely breaks flask-cors, causing unused keyword arguments to throw "TypeError: wrapper() got an unexpected keyword argument"

Reverting to flask-jwt-extended==3.* fixes both of these issues, negating the need to manually specify endpoints for routes in blueprints.